#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-delve
Version  : 4d8daeb1a884c475b0b63483e3e15727f7af1c90
Release  : 2
URL      : https://github.com/derekparker/delve/archive/4d8daeb1a884c475b0b63483e3e15727f7af1c90.tar.gz
Source0  : https://github.com/derekparker/delve/archive/4d8daeb1a884c475b0b63483e3e15727f7af1c90.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-3.0 LGPL-3.0 MIT
BuildRequires : go
Patch1: 001-build-vars.patch

%description
Delve is a debugger for the Go programming language. The goal of the project is to provide a simple, full featured debugging tool for Go. Delve should be easy to invoke and easy to use. Chances are if you're using a debugger, most likely things aren't going your way. With that in mind, Delve should stay out of your way as much as possible.

%prep
%setup -q -n delve-4d8daeb1a884c475b0b63483e3e15727f7af1c90
%patch1 -p1

%build
export LANG=C
make V=1  %{?_smp_mflags} install

%install
mkdir -p %{buildroot}/usr/bin
cp -pav build/bin/dlv %{buildroot}/usr/bin

%files
%defattr(-,root,root,-)
/usr/bin/dlv
